kikit panelize     --layout 'grid; rows: 3; cols: 6; space: 1.0mm'    --tooling '3hole; hoffset: 2.5mm; voffset: 1.5mm; size: 1.5mm'  --tabs 'fixed; width: 3mm; vcount: 1'     --cuts vcuts      --framing 'railstb; width: 3mm; space: 1mm;'     --post 'millradius: 0.5mm'     SemiSemafor.kicad_pcb panel.kicad_pcb

kikit fab jlcpcb --no-drc --assembly --schematic SemiSemafor.kicad_sch panel.kicad_pcb jlcdata
